// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _ANIMENGINE_FILE_ANIM_H_
#define _ANIMENGINE_FILE_ANIM_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

void anim_file_demo(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
