// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "file_anim.h"
/////////////////////CUSTOM VARIABLES ////////////////////


///////////////////// LVGL VARIABLES ////////////////////
lv_obj_t* file_anim_screen;
lv_obj_t* label1;
lv_obj_t* ui_Label_create;
lv_obj_t* ui_btn_create;

lv_obj_t* ui_Label_start;
lv_obj_t* ui_btn_start;


///////////////////// SCREENS ////////////////////

void ui_event_btn_delete(lv_event_t* e){
    LV_LOG_USER("Start button delete");
}

void ui_event_btn_start(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("Start button clicked");
        lv_obj_remove_event_cb(ui_btn_start, ui_event_btn_delete);
        lv_obj_remove_event_cb(ui_btn_start, ui_event_btn_start);
        lv_obj_add_event_cb(ui_btn_start, ui_event_btn_delete, LV_EVENT_DELETE, NULL);
        lv_obj_add_event_cb(ui_btn_start, ui_event_btn_start, LV_EVENT_CLICKED, NULL);
    }
}

void ui_anim_screen_init(void)
{
    file_anim_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(file_anim_screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(file_anim_screen, lv_color_hex(0x000000),
        LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(file_anim_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    label1 = lv_label_create(file_anim_screen);
    lv_label_set_long_mode(label1, LV_LABEL_LONG_WRAP); /*Break the long lines*/
    lv_label_set_text(label1, "Recolor is not supported for v9 now.");
    lv_obj_set_width(label1, 480); /*Set smaller width to make the lines wrap*/
    lv_obj_set_style_text_align(label1, LV_TEXT_ALIGN_LEFT, 0);
    lv_obj_align(label1, LV_ALIGN_TOP_LEFT, 0, 0);
    lv_obj_set_style_text_color(label1, lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_start = lv_btn_create(file_anim_screen);
    lv_obj_set_width(ui_btn_start, 59);
    lv_obj_set_height(ui_btn_start, 33);
    lv_obj_set_x(ui_btn_start, 110);
    lv_obj_set_y(ui_btn_start, 204);
    lv_obj_set_align(ui_btn_start, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_btn_start, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_btn_start, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_btn_start, lv_color_hex(0xFFFFFF),
        LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_start = lv_label_create(file_anim_screen);
    lv_obj_set_width(ui_Label_start, LV_SIZE_CONTENT); /// 1
    lv_obj_set_height(ui_Label_start, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label_start, 115);
    lv_obj_set_y(ui_Label_start, 204);
    lv_obj_set_align(ui_Label_start, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Label_start, "start");
    lv_obj_set_style_text_color(ui_Label_start, lv_color_hex(0x000000),
        LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_start, 255,
        LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_start, ui_event_btn_delete, LV_EVENT_DELETE, NULL);
    lv_obj_add_event_cb(ui_btn_start, ui_event_btn_start, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_btn_start, ui_event_btn_start, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_btn_start, ui_event_btn_start, LV_EVENT_PRESS_LOST, NULL);
}


void anim_file_demo(void)
{
    lv_disp_t* dispp = lv_disp_get_default();
    lv_theme_t* theme = lv_theme_default_init(
        dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
        false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    ui_anim_screen_init();


    lv_disp_load_scr(file_anim_screen);
}
